### ISSUE TITLE
Integration of cv-frontend-vue repository with the circuitverse (main) repository : part 1

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3768]
### tasks to be done:

- [x] Add the cv-frontend-vue repository into main repository with the help of git submodules

- [x] setup the routes for the new simulator

- [x] update esbuild to configure the build of the vue simulator

### Are you working on this?

Yes
