### ISSUE TITLE
Creation of new api endpoints in the api/v1 format part-1

### ISSUE THREAD

**Issue by Arnabdaz** [CircuitVerse/CircuitVerse#3778]
### Tasks to be done

- [x] Create new api endpoint to fetch user information , check project access , get project details
- [x] Create new api to get project data
- [x] Create new api to update project data

### Are you working on this?

Yes
