### ISSUE TITLE
BucketList - Ankit

### ISSUE THREAD

**Issue by satu0king** [CircuitVerse/CircuitVerse#412]
These are some requirements, Ping me before starting for more details. 

- [x] Add feature link (make it work like a button) in the area below in circuit page
![image](https://user-images.githubusercontent.com/2092958/61591399-213c3d80-abe4-11e9-8a72-a1f8dd3d471a.png)

- [ ] You can work on the autosave feature for the simulator #34
- [ ] Automatically subscribe to emails(for comments) when user creates a project. See (#91, #232)
- [ ] Client Side Circuit Search (#413)
- [x] Update gitter->slack link in about and contribute page: https://circuitverse.org/about and https://circuitverse.org/contribute. Add discord link and discourse link as well. 
- [x] Merge unique tags PR: #333 

This is a bit big
- [x] Create an attributed subscribed (boolean) in users, set it to true, have a page either in rails admin or some other place to send emails to all users who are subscribed (admins only obviously). Yes, for now we will send mails via the default mailer. Later when the time is right we can move to a service like mailchimp. The email should have an unsubscribe button.

**Comment by ciphereck** [comment]
.
