### ISSUE TITLE
Feature Convert all jquery code to vanilla JavaScript

### ISSUE THREAD

**Issue by shauryag2002** [CircuitVerse/CircuitVerse#4189]
### Is your feature request related to a problem? Please describe

Now CircuitVerse is not using jquery and shifting to vanilla Javascript

### Describe the solution you'd like

convert all jquery files to vanilla JavaScript

### Task(files) to be done(converted):
- app/assets/
- [ ] app/assets/javascripts/restrictElements.js
- [ ] app/assets/javascripts/scroll.js
- [ ] app/assets/javascripts/webpush.js.erb
- app/javascript
- [ ] app/javascript/controllers/assignment_controller.js
- [ ] app/javascript/controllers/groups_controller.js

### Additional context

Note : Additional files will be appended to this issue.

### Are you working on this?

Yes

**Comment by shauryag2002** [comment]
@tanmoysrt @vedant-jain03 @VaibhavUpreti  Please assign this issue to me !

**Comment by tanmoysrt** [comment]
> @tanmoysrt @vedant-jain03 @VaibhavUpreti Please assign this issue to me!

If you want to work on this, I guess We need to split it into smaller parts and sub-issues. 
@vedant-jain03 @tachyons can say better on it.

**Comment by DhairyaMajmudar** [comment]
@tanmoysrt @shauryag2002 I would also like to work on these tasks.

**Comment by YashGupt29** [comment]
i can also contribute in this converting jquery to js as jquery is quiet old

**Comment by theslowdeveloper** [comment]
can help as well

**Comment by manthan-sharma-23** [comment]
Hey there I would also like to work on this project . Thank you!

**Comment by tachyons** [comment]
This is beyond the scope for now
